version: "3.8"
services:
  api:
    restart: unless-stopped
    container_name: dev_api_promo_hunt
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - mongodb
    volumes:
      - ./:/usr/src/app
    networks:
      - promo_hunt_network

  mongodb:
    container_name: dev_db_mongo_promo_hunt
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongo-db:/data/db
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - promo_hunt_network

  mongo-express:
    container_name: dev_web_mongo_express_promo_hunt
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOSTNAME}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${DATABASE_WEB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DATABASE_WEB_PASSWORD}
    depends_on:
      - mongodb
    restart: unless-stopped
    env_file:
      - ./.env
    networks:
      - promo_hunt_network

networks:
  promo_hunt_network:
    driver: bridge

volumes:
  mongo-db:
